// Computes campaign medal times from clean AI runs and writes src/track/medals.js
//   node --import ./tests/hooks.mjs tests/medals.mjs
import fs from 'node:fs';
import { Track } from '../src/track/track.js';
import { CAMPAIGN } from '../src/track/campaign.js';
import { Race } from '../src/game/race.js';
import { Bot } from '../src/game/bot.js';
import { PHYS_DT } from '../src/config.js';
import { medalsFromAuthor } from '../src/game/records.js';

function run(track, skill) {
  const race = new Race(track);
  const bot = new Bot(track.route, race.car, { skill });
  race.reset({ countdown: false });
  let respawns = 0, t = 0;
  race.on('autoRespawn', () => { respawns++; race.respawn(); });
  while (t < 240 && race.state !== 'finished') {
    const input = race.state === 'running' ? bot.update(race.car, PHYS_DT) : {};
    if (input.respawn) { respawns++; if (!race.respawn()) return null; bot.reset(track.route.nearest(race.car.pos.toArray())); }
    race.step(PHYS_DT, input);
    t += PHYS_DT;
  }
  return race.state === 'finished' && respawns === 0 ? race.finishTime : null;
}

const out = {};
for (const def of CAMPAIGN) {
  const track = new Track({ ...def.build(), id: def.id });
  let best = null;
  const times = [];
  for (const skill of [0.95, 1.0, 1.05, 1.1, 1.15, 1.2]) {
    const t = run(track, skill);
    times.push(t == null ? 'x' : t.toFixed(3));
    if (t != null && (best == null || t < best)) best = t;
  }
  const author = Math.ceil((best * 1000) / 10) * 10;
  out[def.id] = medalsFromAuthor(author);
  console.log(def.id, def.name.padEnd(16), 'runs', times.join(' '), '-> author', author);
}
const src = `// Generated by tests/medals.mjs from clean AI runs. Times in milliseconds.\nexport const CAMPAIGN_MEDALS = ${JSON.stringify(out, null, 2)};\n`;
fs.writeFileSync(new URL('../src/track/medals.js', import.meta.url), src);
console.log('wrote src/track/medals.js');
