// Generated by tests/medals.mjs from clean AI runs. Times in milliseconds.
export const CAMPAIGN_MEDALS = {
  "c01": {
    "author": 26870,
    "gold": 29020,
    "silver": 33590,
    "bronze": 41650
  },
  "c02": {
    "author": 32880,
    "gold": 35520,
    "silver": 41100,
    "bronze": 50970
  },
  "c03": {
    "author": 32030,
    "gold": 34600,
    "silver": 40040,
    "bronze": 49650
  },
  "c04": {
    "author": 34050,
    "gold": 36780,
    "silver": 42570,
    "bronze": 52780
  },
  "c05": {
    "author": 26010,
    "gold": 28100,
    "silver": 32520,
    "bronze": 40320
  },
  "c06": {
    "author": 37020,
    "gold": 39990,
    "silver": 46280,
    "bronze": 57390
  },
  "c07": {
    "author": 25110,
    "gold": 27120,
    "silver": 31390,
    "bronze": 38930
  },
  "c08": {
    "author": 26880,
    "gold": 29040,
    "silver": 33600,
    "bronze": 41670
  },
  "c09": {
    "author": 30840,
    "gold": 33310,
    "silver": 38550,
    "bronze": 47810
  },
  "c10": {
    "author": 41920,
    "gold": 45280,
    "silver": 52400,
    "bronze": 64980
  }
};
