// Generated by tests/medals.mjs from clean AI runs. Times in milliseconds.
export const CAMPAIGN_MEDALS = {
  "c11": {
    "author": 32310,
    "gold": 34900,
    "silver": 40390,
    "bronze": 50090
  },
  "n02": {
    "author": 30130,
    "gold": 32550,
    "silver": 37670,
    "bronze": 46710
  },
  "n03": {
    "author": 39700,
    "gold": 42880,
    "silver": 49630,
    "bronze": 61540
  },
  "n04": {
    "author": 37840,
    "gold": 40870,
    "silver": 47300,
    "bronze": 58660
  },
  "n05": {
    "author": 33430,
    "gold": 36110,
    "silver": 41790,
    "bronze": 51820
  },
  "n06": {
    "author": 31960,
    "gold": 34520,
    "silver": 39950,
    "bronze": 49540
  },
  "n07": {
    "author": 32200,
    "gold": 34780,
    "silver": 40250,
    "bronze": 49910
  },
  "n08": {
    "author": 32630,
    "gold": 35250,
    "silver": 40790,
    "bronze": 50580
  },
  "n09": {
    "author": 32240,
    "gold": 34820,
    "silver": 40300,
    "bronze": 49980
  },
  "n10": {
    "author": 41270,
    "gold": 44580,
    "silver": 51590,
    "bronze": 63970
  }
};
