// Generated by tests/medals.mjs from clean AI runs. Times in milliseconds.
export const CAMPAIGN_MEDALS = {
  "c01": {
    "author": 24170,
    "gold": 26110,
    "silver": 30220,
    "bronze": 37470
  },
  "c02": {
    "author": 30130,
    "gold": 32550,
    "silver": 37670,
    "bronze": 46710
  },
  "c03": {
    "author": 28990,
    "gold": 31310,
    "silver": 36240,
    "bronze": 44940
  },
  "c04": {
    "author": 31050,
    "gold": 33540,
    "silver": 38820,
    "bronze": 48130
  },
  "c05": {
    "author": 23970,
    "gold": 25890,
    "silver": 29970,
    "bronze": 37160
  },
  "c06": {
    "author": 32990,
    "gold": 35630,
    "silver": 41240,
    "bronze": 51140
  },
  "c07": {
    "author": 21430,
    "gold": 23150,
    "silver": 26790,
    "bronze": 33220
  },
  "c08": {
    "author": 27540,
    "gold": 29750,
    "silver": 34430,
    "bronze": 42690
  },
  "c09": {
    "author": 27830,
    "gold": 30060,
    "silver": 34790,
    "bronze": 43140
  },
  "c10": {
    "author": 37420,
    "gold": 40420,
    "silver": 46780,
    "bronze": 58010
  },
  "c11": {
    "author": 31760,
    "gold": 34310,
    "silver": 39700,
    "bronze": 49230
  }
};
