# GLB (textured) -> simplified mesh with vertex colours -> assets/models/nature.js
import sys, json, base64
import numpy as np, trimesh, fast_simplification
from scipy.spatial import cKDTree

def load(name):
    s = trimesh.load(name + '.glb')
    g = list(s.geometry.values())[0] if hasattr(s, 'geometry') else s
    col = g.visual.to_color().vertex_colors[:, :3].astype(np.float32)
    return np.asarray(g.vertices, np.float64), np.asarray(g.faces, np.int64), col

def bake(name, faces_target):
    v, f, col = load(name)
    # weld the texture seams first, or the simplifier cannot collapse across them
    w = trimesh.Trimesh(v, f, process=False)
    w.merge_vertices(merge_tex=True, merge_norm=True)
    wv, wf = np.asarray(w.vertices, np.float64), np.asarray(w.faces, np.int64)
    red = max(0.0, 1.0 - faces_target / len(wf))
    v2, f2 = fast_simplification.simplify(wv, wf, red)
    # colour of each new vertex: mean of the nearest original vertices
    tree = cKDTree(v)
    d, idx = tree.query(v2, k=6)
    c2 = col[idx].mean(axis=1)
    # base on the ground, unit height, centred
    lo = v2.min(0); hi = v2.max(0)
    h = hi[1] - lo[1]
    v2 = (v2 - np.array([(lo[0] + hi[0]) / 2, lo[1], (lo[2] + hi[2]) / 2])) / h
    # flat low-poly look: unshare vertices so every face gets one colour
    tri = v2[f2].reshape(-1, 3)
    fc = c2[f2].mean(axis=1)
    cols = np.repeat(fc, 3, axis=0)
    # positions quantised to int16 (1/16000 of the height)
    return {
        'pos': base64.b64encode(np.round(tri * 16000).astype(np.int16).tobytes()).decode(),
        'col': base64.b64encode(np.clip(cols, 0, 255).astype(np.uint8).tobytes()).decode(),
        'tris': int(len(f2)),
        'size': [float(hi[0] - lo[0]) / h, 1.0, float(hi[2] - lo[2]) / h],
    }

out = {}
for spec in sys.argv[2:]:
    name, n = spec.split(':')
    out[name] = bake(name, int(n))
    print(name, out[name]['tris'], 'tris', 'size', [round(x, 2) for x in out[name]['size']])
src = ('// Generated by tools/nature (Higgsfield 3D models, simplified, texture baked into\n'
       '// per-face colours). Unit height, base at y = 0. pos: Int16 xyz per corner\n'
       '// (divide by 16000),\n'
       '// col: Uint8 rgb per corner, both base64.\n'
       'export const NATURE = ' + json.dumps(out) + ';\n')
open(sys.argv[1], 'w').write(src)
print('wrote', sys.argv[1], round(len(src) / 1024), 'KB')
